<?php
$db = new SQLite3('mysqlitedb.db');
//$db->exec("CREATE TABLE product_category(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, priority INTEGER NOT NULL, parent_id INTEGER NOT NULL, memo TEXT)");

//$db->exec("CREATE TABLE spu(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, info_list TEXT, category_id INTEGER, FOREIGN KEY(category_id) REFERENCES product_category(id) ON DELETE RESTRICT ON UPDATE RESTRICT)");

//$db->exec("CREATE TABLE sku(id INTEGER PRIMARY KEY AUTOINCREMENT, price INTEGER, stock INTEGER, info_1 TEXT, info_2 TEXT, info_3 TEXT, info_4 TEXT, info_5 TEXT, img Text, spu_id INTEGER, FOREIGN KEY(spu_id) REFERENCES spu(id) ON DELETE RESTRICT ON UPDATE RESTRICT)");

//$db->exec("CREATE TABLE cart(id INTEGER PRIMARY KEY AUTOINCREMENT, cookie TEXT UNIQUE, user_id INTEGER)");
//$db->exec("CREATE TABLE cart_item(id INTEGER PRIMARY KEY AUTOINCREMENT, cart_id INTEGER, sku_id INTEGER UNIQUE, quantity INTEGER, FOREIGN KEY(cart_id) REFERENCES cart(id) ON DELETE RESTRICT ON UPDATE RESTRICT, FOREIGN KEY(sku_id) REFERENCES sku(id) ON DELETE RESTRICT ON UPDATE RESTRICT)");

?>